#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "shell_parser.y".
#

require 'racc/parser.rb'

require_relative 'shell_tokenizer'
class ShellParser < Racc::Parser

module_eval(<<'...end shell_parser.y/module_eval...', 'shell_parser.y', 33)
ParseError = Class.new(StandardError)

# Parse a shell command string into an array of segment strings.
# Each segment is a "simple command" (a sequence of words).
# Raises ParseError for unsafe constructs (redirects, substitutions, etc.)
def self.parse(command)
  new(command).parse!
end

def initialize(command)
  @tokens = ShellTokenizer.tokenize(command.to_s)
  @pos    = 0
end

# Parse and return an array of command segment strings.
# e.g. "ls | grep x" => ["ls", "grep x"]
#      "echo hi && pwd" => ["echo hi", "pwd"]
def parse!
  raise ParseError, "empty command" if @tokens.empty?
  tree = do_parse
  # tree is [[["ls"], ["grep", "x"]], ...] (list of pipelines of simple_commands)
  # Flatten to segment strings: each simple_command's words joined by space.
  tree.flatten(1).map { |words| words.join(' ') }
end

def next_token
  return [false, nil] if @pos >= @tokens.length

  kind, text = @tokens[@pos]
  @pos += 1

  case kind
  when :word     then [:word, text]
  when :pipe     then [:pipe, nil]
  when :and      then [:and, nil]
  when :or       then [:or, nil]
  when :semi     then [:semi, nil]
  when :pipe_and then [:pipe_and, nil]
  when :danger   then raise ParseError, "unsafe construct: #{text}"
  else raise ParseError, "unknown token kind: #{kind}"
  end
end

def error_token(token, value, lvalue)
  raise ParseError, "unexpected token near: #{token.inspect}"
end

def unexpected_token(token, value, vstack)
  raise ParseError, "syntax error at: #{token.inspect}"
end
...end shell_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     7,     8,     9,    10,    11,    10,    11,    10,    11,    10,
    11,     5,     6,    12,    13,     5,     5,     5,     5,     5,
    12,    12 ]

racc_action_check = [
     2,     2,     2,     3,     3,    14,    14,    15,    15,    16,
    16,     0,     1,     4,     6,     7,     8,     9,    10,    11,
    17,    18 ]

racc_action_pointer = [
     4,    12,    -2,    -2,     6,   nil,    14,     8,     9,    10,
    11,    12,   nil,   nil,     0,     2,     4,    13,    14 ]

racc_action_default = [
   -11,   -11,    -1,    -2,    -6,    -9,   -11,   -11,   -11,   -11,
   -11,   -11,   -10,    19,    -3,    -4,    -5,    -7,    -8 ]

racc_goto_table = [
     3,    17,    18,     1,     2,   nil,   nil,    14,    15,    16 ]

racc_goto_check = [
     3,     4,     4,     1,     2,   nil,   nil,     3,     3,     3 ]

racc_goto_pointer = [
   nil,     3,     4,     0,    -9 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 9, :_reduce_1,
  1, 10, :_reduce_2,
  3, 10, :_reduce_3,
  3, 10, :_reduce_4,
  3, 10, :_reduce_5,
  1, 11, :_reduce_6,
  3, 11, :_reduce_7,
  3, 11, :_reduce_8,
  1, 12, :_reduce_9,
  2, 12, :_reduce_10 ]

racc_reduce_n = 11

racc_shift_n = 19

racc_token_table = {
  false => 0,
  :error => 1,
  :semi => 2,
  :and => 3,
  :or => 4,
  :pipe => 5,
  :pipe_and => 6,
  :word => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "semi",
  "and",
  "or",
  "pipe",
  "pipe_and",
  "word",
  "$start",
  "command",
  "list",
  "pipeline",
  "simple_command" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'shell_parser.y', 5)
  def _reduce_1(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 8)
  def _reduce_2(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 10)
  def _reduce_3(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 12)
  def _reduce_4(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 14)
  def _reduce_5(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 17)
  def _reduce_6(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 19)
  def _reduce_7(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 21)
  def _reduce_8(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 24)
  def _reduce_9(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'shell_parser.y', 26)
  def _reduce_10(val, _values, result)
     result = val[0] + [val[1]]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ShellParser
